---
- name: Update & Upgrade
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: true

- name: Install MySQL & other packages
  ansible.builtin.apt:
    name:
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present

- name: Create mysql database
  community.mysql.mysql_db:
    name: '{{ db_name }}'
    state: present

- name: Config mysql user
  community.mysql.mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_pass }}'
    encrypted: true
    priv: '{{ db_name }}.*:ALL'
    state: present

- name: Enable remote login to mysql
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: true
  notify:
    - Restart mysql

- name: Menambahkan repository php
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Instal paket php8.0, phpmyadmin dan beberapa dependensi.
  ansible.builtin.apt:
    name:
      - php8.0-mysql
      - php8.0-mbstring
      - php8.0-xml
      - php8.0-curl
      - php8.0-cli
      - php8.0-common
      - php8.0-gd
      - libapache2-mod-php8.0
      - phpmyadmin
    state: present
    update_cache: true

- name: Konfigurasi debconf untuk phpMyAdmin
  debconf:
    name: phpmyadmin
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
    - { question: 'phpmyadmin/dbconfig-install', value: 'true', vtype: 'boolean' }
    - { question: 'phpmyadmin/app-password-confirm', value: '{{ db_pass }}', vtype: 'password' }
    - { question: 'phpmyadmin/mysql/admin-pass', value: '{{ db_pass }}', vtype: 'password' }
    - { question: 'phpmyadmin/mysql/app-pass', value: '{{ db_pass }}', vtype: 'password' }
    - { question: 'phpmyadmin/reconfigure-webserver', value: 'apache2', vtype: 'multiselect' }

- name: Configure phpMyAdmin Apache
  ansible.builtin.template:
    src: phpmyadmin.conf.j2
    dest: /etc/apache2/conf-available/phpmyadmin.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable phpMyAdmin Apache configuration
  ansible.builtin.command:
    cmd: a2enconf phpmyadmin.conf
  notify:
    - Restart apache

- name: Enable PHP module
  ansible.builtin.command:
    cmd: a2enmod php8.0

- name: Enable rewrite module
  ansible.builtin.command:
    cmd: a2enmod rewrite

- name: Set mode
  ansible.builtin.file:
    path: /usr/share/phpmyadmin
    state: directory
    recurse: true
    mode: "775"

- name: Set ownership
  ansible.builtin.file:
    path: /usr/share/phpmyadmin
    owner: www-data
    group: www-data
    recurse: true
    mode: "0775"
  notify:
    - Restart apache