version: '3.8'

services:
  app:
    build: .
    volumes:
        - ./:/usr/src/app
    ports:
        - "8501:8501"
    networks:
      - app-network
    depends_on:
      - nginx
  nginx:
    image: nginx:1.15.12-alpine
    restart: unless-stopped
    privileged: true
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/certs:/certs
      - ./nginx/nginx.secure.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
