bootcmd:
  - echo 192.168.0.1 >> /etc/hosts
runcmd:
 - [ ls, -l, / ]
 - [ sh, -xc, "echo $(date) ': hello world!'" ]
ssh_pwauth: true
disable_root: false
chpasswd:
  list: |
     root:password
  expire: false
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCHbYYh5tqg9exO3nqzWzCA4sawLlh7hRMdmFccxkhcRtQxi75tNGv92trAdWW1nbXLz9ZIybGg2uQPr0hgVJrnkgcNM3zEN0a83RcfAw0klci31OEU/gRpqqRmZMyRRtPrhavk78FHMwxpHBGpyxrVCSeXwKln+EtcLtjrWBQUatFR7+c19OXffmizjoI1Qyw8FOZETy8Hwu+K6EH3hQ3kPcA+AFHA3lxd9BRw/XuNG9MHXWL+0cmqeddGKG0OWdTvcU0/ZSoIR9FO3yei+Rbtyos5QkOmiSVv6hwipIkx0ji4CeUJ9XRjkNsIP9FHpwuqkLUMqg4K4TjG4X4FxT3xh/jRQsc3BYPCVhzbfws+C7iAYxOvlQm1ikZBsvRQkwbc4aS+NayxfKqn7c8HV6zFc8FRJf8c6h/odCEYs2J7OdZKdOuDVwZUqvqBvDnxPAe8YMVt8iG5jwqa2XFz+GNkJLdyvGIk8IOq7hRrhBu6rtDkV7SHOoKfXeD5g1im91LwZzRQfqfmD2swF8MoLVOI3YRPAYYqB3MqeMpdwTzW1yOLLMkfyJOA8iw5vhXXQt1Ed6in3Dtvc4p8rfRiUASZD/PWHFdlqS/ybGSlh+1C5BjJb601sKozZmAR5f8KS6y34NoYoMjg5Ug0LHGX3cetN4QeetHLvvrWcV8ZpmQWw== pepuhodaniel93@gmail.com
final_message: "The system is finally up, after $UPTIME seconds"